# Generated by Django 5.1.1 on 2024-10-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_session_assistantmessage_usermessage'),
        ('llm_agents', '0002_alter_vizualization_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
