# Generated by Django 5.1.1 on 2024-10-16 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_svg_data_assistantmessage_svg_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
