# Generated by Django 5.1.1 on 2024-10-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_assistantmessage_uuid_usermessage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='reply_to_assistant_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og_user_message', to='chat.assistantmessage'),
        ),
    ]
