# Generated by Django 5.1.1 on 2024-10-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_dataset_uri_dataset_publicurl_dataset_s3uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='chat.chatsession'),
        ),
    ]
